### ISSUE TITLE
Sequence only predictions

### ISSUE THREAD

**Issue by VKonstantakos** [Peppags/C-RNNCrispr#1]
Is it possible to use this particular model to make predictions based only on sequence composition features e.g. to reproduce the results in Table 6 of your study? If so, could you describe the process you used?

Deleting (commenting out) the epigenetic branch of the network gives variable results (based only on the sgRNA branch).

Any help would be appreciated. Thank you.

**Comment by Peppags** [comment]
Hi,
You need to build the C-RNNCrispr_seq_only model by removing the epigenetic branch from the C-RNNCrispr framework and train it from scratch on the benchmark dataset, then fine tune on cell line of interest datasets.

**Comment by VKonstantakos** [comment]
Hello,

Just to clarify, if I have all the features available (sequence + epigenetic) for some examples I can use the model as is (with the available weights) to make predictions?

However, if I only have the sequences I should train it from scratch after removing the epigenetic branch.

Is that correct?

**Comment by Peppags** [comment]
That’s right.

**Comment by VKonstantakos** [comment]
Thank you very much for your help.
